# Generated by Django 3.2.5 on 2022-06-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='shirt', max_length=100),
            preserve_default=False,
        ),
    ]
